steps:
  # Pull docker image
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$_IMAGE_PROJECT/ringesentralen-backend:latest

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ringesentralen-prod-backend']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
          'beta',
          'run',
          'deploy',
          'ringesentralen-prod-backend',
          '--image', 'gcr.io/$PROJECT_ID/ringesentralen-prod-backend',
          '--allow-unauthenticated',
          '--platform=managed',
          '--region=europe-north1'
      ]

# Image name
images: ['gcr.io/$PROJECT_ID/ringesentralen-prod-backend']