steps:
  # Create docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ringesentralen-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ringesentralen-backend']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta',
      'run',
      'deploy',
      'ringesentralen-backend',
      '--image', 'gcr.io/$PROJECT_ID/ringesentralen-backend',
      '--region',
      'europe-north1',
      '--allow-unauthenticated'
    ]

# Image name
images: ['gcr.io/$PROJECT_ID/ringesentralen-backend']
