steps:

  # Create docker image
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build --build-arg=DBUSER=$$DBUSER --build-arg=DBPASSWORD=$$DBPASSWORD --build-arg=QuarkusMailerUsername=$$QuarkusMailerUsername --build-arg=QuarkusMailerPassword=$$QuarkusMailerPassword -t gcr.io/$PROJECT_ID/ringesentralen-backend .
    secretEnv: ['DBUSER', 'DBPASSWORD', 'QuarkusMailerUsername', 'QuarkusMailerPassword']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ringesentralen-backend']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
      'beta',
      'run',
      'deploy',
      'ringesentralen-backend',
      '--image', 'gcr.io/$PROJECT_ID/ringesentralen-backend',
      '--allow-unauthenticated',
      '--platform=managed',
      '--region=europe-north1'
      ]

# Image name
images: ['gcr.io/$PROJECT_ID/ringesentralen-backend']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
    env: 'DBUSER'
  - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    env: 'DBPASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/quarkus_mailer_username/versions/latest
    env: 'QuarkusMailerUsername'
  - versionName: projects/$PROJECT_ID/secrets/quarkus_mailer_password/versions/latest
    env: 'QuarkusMailerPassword'