steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    timeout: 1800s
    args:
      - --build-arg=DBUSER=$$DBUSER
      - --build-arg=DBPASSWORD=$$DBPASSWORD
      - --build-arg=QuarkusMailerUsername=$$QuarkusMailerUsername
      - --build-arg=QuarkusMailerPassword=$$QuarkusMailerPassword
      - --cache=true
      - --destination=gcr.io/$PROJECT_ID/ringesentralen-backend
    secretEnv: ['DBUSER', 'DBPASSWORD', 'QuarkusMailerUsername', 'QuarkusMailerPassword']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'ringesentralen-backend',
        '--image', 'gcr.io/$PROJECT_ID/ringesentralen-backend',
        '--allow-unauthenticated',
        '--platform=managed',
        '--region=europe-north1',
      ]

timeout: 1800s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DBUSER'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DBPASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/quarkus_mailer_username/versions/latest
      env: 'QuarkusMailerUsername'
    - versionName: projects/$PROJECT_ID/secrets/quarkus_mailer_password/versions/latest
      env: 'QuarkusMailerPassword'