steps:

  # github-brukarnamn
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=github-user --format='get(payload.data)' | tr '_-' '/+' | base64 -d > github_user.txt" ]

 # github-passord
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=github-password --format='get(payload.data)' | tr '_-' '/+' | base64 -d > github_password.txt" ]

 # debug
  - name: gcr.io/cloud-builders/gcloud
    id: debug
    entrypoint: 'bash'
    args:
      - '-c'
      - cat github_user.txt

  # Create docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GH_USER=$(cat github_user.txt) && export GH_PASSWORD=$(cat github_password.txt) && docker build --build-arg github_user_in=$GH_USER --build-arg github_password_in=$GH_PASSWORD -t gcr.io/$PROJECT_ID/ringesentralen-backend .

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ringesentralen-backend']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
      'beta',
      'run',
      'deploy',
      'ringesentralen-backend',
      '--image', 'gcr.io/$PROJECT_ID/ringesentralen-backend',
      '--region',
      'europe-north1',
      '--allow-unauthenticated'
    ]

# Image name
images: ['gcr.io/$PROJECT_ID/ringesentralen-backend']
