# Use root/example as user/password credentials
# this is copy-paste from https://hub.docker.com/_/mysql/
# run this with docker-compose -f mysql.yaml
services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ringesentralen_test
      TZ: UTC
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"
    environment:
      TZ: UTC