INSERT IGNORE INTO `resultat` (id, navn, displaytext, skalSkjules, svarte)
VALUES (0, 'Ikke svar', 'Ikke svar', 0, 0),
       (1, 'Vil ikke ringes før valget, men gjerne etterpå', 'Vil ikke ringes før valget, men gjerne etterpå', 0, 1),
       (2, 'Trenger ikke å bli oppringt igjen (slettes fra alle lister)', 'Trenger ikke å bli oppringt igjen', 0, 1),
       (3, 'Trenger oppfølging av toppkandidat (husk å skrive stikkord om tema i kommentarfeltet)', 'Trenger oppfølging', 0, 1),
       (4, 'Passet ikke, må bli oppringt på spesifikt tidspunkt', 'Ba om å bli oppringt på spesifikt tidspunkt.', 0, 1),
       (5, 'Vil bli valgkampfrivillig og aktiv i et lokallag', 'Vil bli valgkampfrivillig og aktiv i et lokallag', 0, 1),
       (6, 'Vil bli valgkampfrivillig (henvis til rødt.no/frivillig, og si at de også får en e-post med info)',
        'Vil bli valgkampfrivillig (henvis til rødt.no/frivillig, og si at de også får en e-post med info om hvordan man kan melde seg.)',
        0, 1),
       (7, 'Nei', 'Nei', 0, 1),
       (8,
        'Vil bli aktiv i et lokallag(Vi følger opp aktivt med nærmeste lokallag. Om de sier at det ikke finnes lokallag der de bor, fortell hvordan man kan melde seg som kontaktperson og starte lokallag).',
        'Vil bli aktiv i et lokallag(Vi følger opp aktivt med nærmeste lokallag. Om de sier at det ikke finnes lokallag der de bor, fortell hvordan man kan melde seg som kontaktperson og starte lokallag).',
        0, 1),
       (9, 'Samtale startet', 'Samtale startet', 1, 0),
       (10, 'Flere enn to ikke-svar', 'Flere enn to ikke-svar', 0, 0),
       (11, 'Svarte', 'Svarte', 0, 1),
       (12, 'Ring tilbake', 'Ring tilbake', 0, 1),
       (13, 'Ugyldig svar', 'Ugyldig svar', 0, 1);